# Generated by Django 2.0.5 on 2018-05-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0002_auto_20180529_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('weights', models.TextField()),
                ('values', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TasksStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('time_submitted', models.FloatField(null=True)),
                ('time_started', models.FloatField(null=True)),
                ('time_completed', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CeleryResults',
        ),
        migrations.AddField(
            model_name='solutions',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.TasksStats', to_field='task_id'),
        ),
    ]
